name: TDC_Multiscale_CatAll_ServerVoxel_DDP_30ep

model:
  type: multiscale
  base_dim: 32
  fusion_type: cat_all
  qkv_mode: rgb_qk_event_v
  late_fusion_mode: cat
  window_size: 8
  num_heads: 4
  qk_norm: false
  event_encoder_type: 2d
  attention_dim: 2d
  temporal_window: 2

loss:
  type: l1
  edge_weight: 0.05

datasets:
  train:
    dataset_type: server_voxel
    blur_root: /data1/YW/DVS_DATA/voxel_grid/train/blur
    gt_root: /data1/YW/DVS_DATA/voxel_grid/train/gt
    event_root: /data1/YW/DVS_DATA/voxel_grid/train/event_0.1_0.1
    event_ext: .npy
    event_bins: 6
    patch_size: 256
    batch_size: 1
    num_workers: 4
    prefetch_factor: 2
    norm_event: true
  val:
    dataset_type: server_voxel
    blur_root: /data1/YW/DVS_DATA/voxel_grid/test/blur
    gt_root: /data1/YW/DVS_DATA/voxel_grid/test/gt
    event_root: /data1/YW/DVS_DATA/voxel_grid/test/event_0.1_0.1
    event_ext: .npy
    event_bins: 6
    patch_size: 256
    norm_event: true

train:
  num_epochs: 30
  learning_rate: 0.0002

path:
  experiments_root: /data1/jzy/experiments
  resume_state: ~
