name: TDC_LateFusion_Aplus_H5_2060

model:
  type: late_fusion
  base_dim: 32
  fusion_type: hybrid
  qkv_mode: rgb_qk_event_v
  late_fusion_mode: kv_2d_k_tdc_v_plus
  window_size: 8
  num_heads: 4
  qk_norm: false
  event_encoder_type: 2d
  attention_dim: 2d
  temporal_window: 2

loss:
  type: l1
  edge_weight: 0.05

datasets:
  train:
    dataset_type: h5
    dataroot: E:/GOPRO/GOPRO/train
    patch_size: 256
    batch_size: 4
    num_workers: 2
    prefetch_factor: 4
    max_open_h5: 2
    norm_event: true
  val:
    dataset_type: h5
    dataroot: E:/GOPRO/GOPRO/test
    patch_size: 256
    max_open_h5: 2
    norm_event: true

train:
  num_epochs: 30
  learning_rate: 0.0002

path:
  experiments_root: ./experiments
  resume_state: ~
